import yfinance as yf, pandas as pd, numpy as np
import warnings; warnings.filterwarnings('ignore')
import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

df = yf.download('8064.TWO', period='300d', progress=False, auto_adjust=True)
if isinstance(df.columns, pd.MultiIndex): df.columns = df.columns.droplevel(1)

c = df['Close']
price = float(c.iloc[-1])
sma10 = float(c.rolling(10).mean().iloc[-1])
sma20 = float(c.rolling(20).mean().iloc[-1])
sma50 = float(c.rolling(50).mean().iloc[-1])
sma200= float(c.rolling(200).mean().iloc[-1])
hl = df['High'] - df['Low']
hc = abs(df['High'] - df['Close'].shift())
lc = abs(df['Low']  - df['Close'].shift())
atr = float(pd.concat([hl,hc,lc],axis=1).max(axis=1).rolling(14).mean().iloc[-1])
d = c.diff()
rs = d.where(d>0,0).rolling(14).mean() / (-d.where(d<0,0)+1e-10).rolling(14).mean()
rsi = float((100-(100/(1+rs))).iloc[-1])
dev = (price - sma20) / sma20 * 100
week_high = float(df['High'].tail(5).max())
month_low = float(df['Low'].tail(20).min())

print(f"8064 東捷 進場分析 ({df.index[-1].date()})")
print("=" * 50)
print(f"現價:       NT${price:.0f}")
print(f"SMA10:      NT${sma10:.0f}  ({(price-sma10)/sma10*100:+.1f}%)")
print(f"SMA20:      NT${sma20:.0f}  (乖離 {dev:+.1f}%)")
print(f"SMA50:      NT${sma50:.0f}  ({(price-sma50)/sma50*100:+.1f}%)")
print(f"RSI(14):    {rsi:.1f}")
print(f"ATR(14):    NT${atr:.1f}  (日波動幅)")
print()
print("=" * 50)
print("  進場策略建議")
print("=" * 50)
print()

if dev > 15:
    print("⚠️  現在乖離過大 (+15.4%)，不建議追高")
    print()
    print("方案A：等回調後進場（較安全）")
    print(f"  理想買點1: NT${sma10:.0f}  (回測SMA10，-{(price-sma10)/price*100:.1f}%)")
    print(f"  理想買點2: NT${sma20:.0f}  (回測SMA20，-{(price-sma20)/price*100:.1f}%)")
    print()
    print("方案B：等 MACD 收腳 + 跳空後進場")
    print("  → MACD柱狀體由正翻負 = 短期回調開始")
    print("  → 等柱狀體縮短 + 隔日跳空開高 = 最佳進場")
    print()
    print("方案C：現在小量試單 (30%)，回調後加碼")
    print(f"  試單價: NT${price:.0f}")
    print(f"  加碼區: NT${sma10:.0f}~NT${sma20:.0f}")
    print(f"  止損:   NT${price - 2*atr:.0f}  (現價 -2ATR = -{2*atr/price*100:.1f}%)")

print()
print("=" * 50)
print("  出場/停利判斷（不要猜高點）")
print("=" * 50)
print()
print("  繼續持有條件（全部符合才抱住）：")
print("  ✅ 週線 MACD 快線 > 0")
print("  ✅ 月線 MACD 快線 > 0")
print("  ✅ 股價站在 SMA50 之上")
print()
print("  出場訊號（出現任一即減碼）：")
print("  🔴 週線 MACD 快線跌破 0")
print("  🔴 月線 MACD 快線跌破 0")
print(f"  🔴 股價跌破 SMA50 (NT${sma50:.0f})")
print()
print("  現在三個條件全部✅ → 多頭結構完整")
print(f"  目前週線MACD=+17.57，月線MACD=+13.78，SMA50差距+{(price-sma50)/sma50*100:.0f}%")
print("  → 出場條件遠未觸發")
